name: Functional UI Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs every hour on the hour (UTC time)

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Sanity UI Tests
        run: npx playwright test tests/SanityTesting

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-report
          path: playwright-report/
