name: Visual Regression Tests

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  visual-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Get all Visual Test Files
        id: get-files
        run: |
          echo "files<<EOF" >> $GITHUB_OUTPUT
          find tests/VisualTesting -name '*.mjs' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Visual Tests Individually and Rename Reports
        run: |
          mkdir -p renamed-visual-reports
          while IFS= read -r file; do
            filename=$(basename "$file" .spec.mjs)
            echo "Running $file"
            npx playwright test "$file" --project=chromium || true
            mv playwright-report "renamed-visual-reports/$filename"
          done <<< "${{ steps.get-files.outputs.files }}"

      - name: Upload All Visual Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-visual-reports
          path: renamed-visual-reports/
