name: Visual Regression Tests

on:
  schedule:
    # Runs daily at 12:00 AM IST (India Standard Time = UTC+5:30).
    # GitHub Actions cron uses UTC, so 12:00 AM IST = 18:30 UTC (previous day).
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  visual-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Clean old diffs
        run: rm -rf screenshots/diffs/*

      - name: Run Visual Regression Tests
        run: npx playwright test tests/VisualTesting

      - name: Upload Visual Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-report
          path: playwright-report/

      - name: Upload Screenshot Diffs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs
          path: screenshots/diffs/
