name: Visual Regression - VisualTesting Folder

on:
  # nightly at 12:00 AM IST (IST = UTC+5:30 => 12:00 IST = 18:30 UTC previous day)
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  list-visual-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.result }}
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find .mjs files in tests/VisualTesting and create matrix
        id: create-matrix
        run: |
          # find only files directly under tests/VisualTesting (change -maxdepth if nested folders exist)
          files=$(bash -lc "find tests/VisualTesting -maxdepth 1 -type f -name '*.mjs' -print | sort")
          echo "Discovered files:"
          echo "$files" || true

          # convert to JSON array for matrix
          arr=()
          while IFS= read -r f; do
            [ -n "$f" ] && arr+=("\"$f\"")
          done <<< "$files"

          if [ ${#arr[@]} -eq 0 ]; then
            echo "No .mjs files found in tests/VisualTesting"
            echo "::set-output name=result::[]"
          else
            json=$(printf "[%s]" "$(IFS=,; echo "${arr[*]}")")
            echo "matrix json: $json"
            echo "::set-output name=result::$json"
          fi

  run-visual-tests:
    needs: list-visual-files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.list-visual-files.outputs.matrix) }}

    steps:
      - name: Checkout repository (required for test files)
        uses: actions/checkout@v3

      - name: Debug - which file will run
        run: |
          echo "Matrix entry: '${{ matrix.file }}'"
          ls -l "${{ matrix.file }}" || true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Ensure diffs folder exists
        run: mkdir -p screenshots/diffs

      - name: Run Playwright for this exact spec file
        run: |
          echo "Running: npx playwright test '${{ matrix.file }}'"
          # run the exact file path so Playwright cannot pick same-basename files from other folders
          npx playwright test "${{ matrix.file }}" --reporter=list

      - name: Upload Visual Report (per-file)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-report-${{ matrix.file }}
          path: playwright-report/

      - name: Upload Screenshot Diffs (per-file)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs-${{ matrix.file }}
          path: screenshots/diffs/

  aggregate:
    needs: run-visual-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Summary note
        run: echo "All VisualTesting matrix jobs completed. Check per-file artifacts for reports and diffs."
